# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml

name = "hugo-kg-shortcodes"
license = "MIT"
licenselink = "https://github.com/kevingimbel/hugo-kg-shortcodes/blob/master/LICENSE"
description = "Collection of hugo shortcodes"
homepage = "https://github.com/kevingimbel/hugo-kg-shortcodes"
tags = ['shortcodes']
features = ['codepen', 'caniuse', 'mastodon']
min_version = "0.41"

[author]
  name = "Kevin Gimbel"
  homepage = "https://kevingimbel.de"