# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml

name = "kg-hugo-shortcodes-theme"
license = "MIT"
licenselink = "https://github.com/kevingimbel/kg-hugo-shortcodes-theme/blob/master/LICENSE"
description = "Collection of hugo shortcodes"
homepage = "https://github.com/kevingimbel/kg-hugo-shortcodes-theme"
tags = ['shortcodes']
features = ['codepen', 'caniuse', 'mastodon']
min_version = "0.41"

[author]
  name = "Kevin Gimbel"
  homepage = "https://kevingimbel.de"